
name: Run MATLAB Script on GitHub-Hosted Runner
on: push
jobs:
  my-job:
    name: Run MATLAB Script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
      
      - name: Run build
        uses: matlab-actions/run-build@v2.4.0

  my-second-job:
    name: Run MATLAB Script Again
    runs-on: ubuntu-latest
    needs: my-job
    steps:
      - uses: actions/checkout@v3
      
      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
      
      - name: Run build
        uses: matlab-actions/run-build@v2.4.0

